"""Write report/Project_Report.md and the README results section from the ACTUAL
result files in results/reports/.  Nothing here is typed in by hand: rerun this
after retraining and every number in the report and README updates.

Usage:
    python src/make_report.py
"""
from __future__ import annotations

import re
import sys
from datetime import date

import config as C
from utils import load_json

README = C.BASE_DIR / "README.md"
REPORT = C.REPORT_DOC_DIR / "Project_Report.md"


def _load(name):
    p = C.REPORT_DIR / name
    return load_json(p) if p.exists() else None


def _f(v, d=4):
    return "—" if v is None else f"{v:.{d}f}"


def results_table(results) -> str:
    lines = ["| Model | Accuracy | Macro Precision | Macro Recall | Macro F1 | Training time (s) "
             "| Inference (ms/image) | Parameters | Weights |",
             "|---|---|---|---|---|---|---|---|---|"]
    for r in results:
        lines.append(
            f"| {r['model']} | {_f(r['accuracy'])} | {_f(r['macro_precision'])} | "
            f"{_f(r['macro_recall'])} | {_f(r['macro_f1'])} | {_f(r.get('training_time_seconds'), 1)} | "
            f"{_f(r['inference_time_ms_per_image'], 3)} | {r['total_parameters']:,} | "
            f"{r.get('weights_source') or '—'} |")
    return "\n".join(lines)


def per_class_table(results) -> str:
    head = "| Class | " + " | ".join(f"{r['model']} F1" for r in results) + " |"
    sep = "|---|" + "---|" * len(results)
    rows = [f"| {c} | " + " | ".join(_f(r["per_class"][c]["f1-score"], 3) for r in results) + " |"
            for c in C.CLASS_NAMES]
    return "\n".join([head, sep, *rows])


def confusions(r) -> list[str]:
    """Human-readable list of off-diagonal confusion-matrix cells."""
    out = []
    cm = r["confusion_matrix"]
    for i, actual in enumerate(C.CLASS_NAMES):
        for j, pred in enumerate(C.CLASS_NAMES):
            if i != j and cm[i][j]:
                out.append(f"{cm[i][j]} × {actual} predicted as {pred}")
    return out


def training_table() -> str:
    lines = ["| Model | Epochs completed | Best epoch | Val. accuracy (best epoch) | Best val. loss "
             "| Batch | LR | Weights |", "|---|---|---|---|---|---|---|---|"]
    for name, cfg in C.MODELS.items():
        t = _load(f"{cfg['slug']}_training.json")
        if t:
            lines.append(f"| {name} | {t['epochs_completed']} / {t['epochs_configured']} | {t['best_epoch']} | "
                         f"{_f(t['val_accuracy_at_best_epoch'])} | {_f(t['best_val_loss'])} | "
                         f"{t['batch_size']} | {t['learning_rate']} | {t['weights_source']} |")
    return "\n".join(lines)


def readme_results(res, best) -> str:
    rs = res["results"]
    s = [f"Measured on the held-out **test set** ({rs[0]['test_samples']} images) — "
         "generated by `python run_project.py all`.\n", results_table(rs), ""]
    if best:
        s.append(f"**Best model (selected automatically): {best['model_name']}** — {best['reason']}\n")
    s.append("![Model comparison](results/graphs/model_comparison.png)")
    return "\n".join(s)


def update_readme(res, best) -> None:
    if not README.exists():
        return
    text = README.read_text(encoding="utf-8")
    block = f"<!-- RESULTS:START -->\n{readme_results(res, best)}\n<!-- RESULTS:END -->"
    text = re.sub(r"<!-- RESULTS:START -->.*?<!-- RESULTS:END -->", lambda m: block, text, flags=re.S)
    README.write_text(text, encoding="utf-8")


def build_report(eda, res, best, summary) -> str:
    rs = res["results"]
    by = {r["model"]: r for r in rs}
    env = (summary or {}).get("environment", {})
    split = (summary or {}).get("split_counts", {})
    best_r = by.get(best["model_name"]) if best else None

    conf_sections = []
    for r in rs:
        errs = confusions(r)
        conf_sections.append(
            f"**{r['model']}** — {r['misclassified']} of {r['test_samples']} test images misclassified."
            + ("\n" + "\n".join(f"- {e}" for e in errs) if errs else " No errors.")
            + f"\n\n![{r['model']} confusion matrix](../{r['confusion_matrix_image']})\n")

    ranked = sorted(rs, key=lambda r: r["macro_f1"], reverse=True)
    ranking = ", ".join(f"{r['model']} ({_f(r['macro_f1'])})" for r in ranked)
    fastest = min(rs, key=lambda r: r["inference_time_ms_per_image"])
    weights = {r["model"]: r.get("weights_source") for r in rs}

    return f"""# AI-Based Semiconductor Wafer Defect Pattern Detection

**A Deep Learning Approach for Automated Wafer-Map Classification**

ML Project Report · Generated {date.today().isoformat()} from the project's result files

**Team:** Balasudhan (RA2411003012164), Kadhir Anand (RA2411003012146), Sarvesh (RA2411003012165), Reenu T R (RA2411003012132)

**Repository:** https://github.com/BALASUDHAN1807/WaferSense-AI

> Every number in this report is read automatically from `results/reports/` by `src/make_report.py`.
> The dataset is **synthetic** (generated by `src/dataset.py`); results are not claims about real fab data.

---

## Abstract

Wafer-map defect patterns indicate which manufacturing step caused yield loss. This project builds an
end-to-end system that classifies a wafer map into one of nine patterns (Center, Donut, Edge-Loc,
Edge-Ring, Loc, Near-Full, Random, Scratch, None). A synthetic dataset of {eda['total_samples']} wafer maps
was generated, validated, analysed and split 70/15/15. Three models — a custom CNN, ResNet50 and
EfficientNetB0 — were trained on identical data and evaluated on the same held-out test set. Ranked by
macro F1: {ranking}. The best model, **{best['model_name']}**, was selected automatically and powers a
command-line prediction engine and a Gradio web application.

## 1. Introduction

Semiconductor wafers are tested die by die; plotting the failing dies gives a *wafer map*. The spatial
shape of the failures is a fingerprint of the root cause — a scratch points to wafer handling, an edge ring
to edge etch or temperature non-uniformity, a centre cluster to deposition or spin-coating problems.
Automating the recognition of these patterns speeds up yield analysis and makes it consistent.

## 2. Problem Statement

Manual and rule-based inspection of wafer maps is slow and inconsistent. We treat defect-pattern
recognition as a **supervised multi-class image-classification problem**: given a 64 × 64 wafer-map image,
predict one of eight defect patterns or the normal class *None*.

## 3. Objectives

1. Build a complete, reproducible pipeline: validation → EDA → preprocessing → training → evaluation.
2. Train and compare a custom CNN, ResNet50 and EfficientNetB0 under the **same** data split.
3. Report accuracy, macro precision/recall/F1, per-class metrics, confusion matrices, training time and
   inference time.
4. Select the best model automatically (highest macro F1).
5. Deliver a prediction engine and a web application that show the class, confidence and all
   class probabilities.

## 4. Background: wafer defect patterns

| Class | Description | Typical process cause |
|---|---|---|
| Center | Defect cluster at the wafer centre | Deposition / spin-coat non-uniformity |
| Donut | Ring-shaped band between centre and edge | Radial CMP or deposition non-uniformity |
| Edge-Loc | Localised cluster at the edge | Handling, clamping, edge-bead removal |
| Edge-Ring | Defects around the rim | Edge etch / temperature non-uniformity |
| Loc | Localised cluster inside the wafer | Local contamination |
| Near-Full | Almost the whole wafer fails | Major process excursion |
| Random | Scattered defects | Particles / contamination |
| Scratch | Thin line of defects | Mechanical scratch (robot, CMP debris) |
| None | No systematic pattern | Normal wafer |

## 5. Dataset Description

| Property | Value |
|---|---|
| Type | **Synthetic**, generated programmatically (`src/dataset.py`, seed {C.SEED}) |
| Images | {eda['total_samples']} PNG files |
| Classes | {eda['num_classes']} ({', '.join(C.CLASS_NAMES)}) |
| Per class | {min(eda['class_counts'].values())}–{max(eda['class_counts'].values())} (balanced: {eda['is_balanced']}) |
| Image size | {eda['image_width']['min']} × {eda['image_height']['min']} pixels, grayscale |
| Encoding | 0 = outside wafer, 127 = good die, 255 = defective die |

Each class is generated with randomised wafer radius, defect position, size, orientation and density
(e.g. partial donut rings, curved or double scratches) plus 0–3 % random background defects on every
wafer, so the classes are not trivially separable. The synthetic data is used because it gives a clean,
balanced, fully labelled benchmark; it does **not** reproduce all the variability of real fab data
(see Limitations).

## 6. Exploratory Data Analysis

Validation (`src/validate_dataset.py`) found no missing, unreadable or duplicate records and no invalid
labels. EDA (`src/eda.py`) results:

- {eda['total_samples']} samples, {eda['num_classes']} classes, perfectly balanced
  ({', '.join(f'{k}: {v}' for k, v in eda['class_counts'].items())}).
- Missing values in `labels.csv`: {eda['missing_values_in_labels_csv']}; duplicate records: {eda['duplicate_records']}.
- Pixel values: {eda['pixel_stats']['unique_values']} (mean {eda['pixel_stats']['mean']}, std {eda['pixel_stats']['std']}).
- Mean defective-die ratio per class:
  {', '.join(f'{k} {v:.3f}' for k, v in eda['defect_ratio_per_class_mean'].items())}.
  Near-Full and Random are dense; Loc, Edge-Loc, Scratch and None are sparse, so the *location and shape*
  of defects — not just their amount — must be learned.

![Class distribution](../results/graphs/class_distribution.png)

![Sample wafer maps](../results/graphs/sample_wafer_maps.png)

![Defect frequency per class](../results/graphs/mean_defect_map_per_class.png)

![Defect ratio per class](../results/graphs/defect_ratio_per_class.png)

## 7. Data Preprocessing

1. Grayscale conversion and resizing to 64 × 64 (nearest-neighbour, so die values are not blended).
2. Normalisation to [0, 1] (divide by 255).
3. Label encoding with one fixed class → index mapping.
4. Stratified split, seed {C.SEED}: **train {split.get('train')}, validation {split.get('val')},
   test {split.get('test')}**, saved to `results/reports/data_split.csv` and reused by every model.
   No image appears in more than one split.
5. Augmentation on the **training set only**: random 90° rotations and horizontal flips. A wafer is
   circular, so these transformations never change the defect class.

For ResNet50 and EfficientNetB0 the 64 × 64 × 1 map is resized to 224 × 224 and replicated to three
channels *inside the model* (custom `WaferToRGB` layer), so all models share identical preprocessing.

## 8. Methodology

### 8.1 Custom CNN
`Input 64×64×1 → Conv2D(32) → MaxPool → Conv2D(64) → MaxPool → Conv2D(128) → MaxPool → Flatten →
Dense(128, ReLU) → Dropout(0.5) → Dense(9, Softmax)` — {by['CNN']['total_parameters']:,} parameters, trained from scratch.

### 8.2 ResNet50 (transfer learning)
ResNet50 backbone (50 layers with residual connections) → GlobalAveragePooling → Dense(128) →
Dropout(0.4) → Dense(9, Softmax). Weights: {weights.get('ResNet50')}.

### 8.3 EfficientNetB0 (transfer learning)
EfficientNetB0 backbone (compound-scaled MBConv blocks) → GlobalAveragePooling → Dense(128) →
Dropout(0.4) → Dense(9, Softmax). Weights: {weights.get('EfficientNetB0')}.

When ImageNet weights can be downloaded the backbone is frozen and only the new head is trained; if the
download is not possible the code falls back to random initialisation with a trainable backbone and records
this (column *Weights* below).

## 9. Experimental Setup

| Item | Value |
|---|---|
| Language / framework | Python {env.get('python')}, TensorFlow {env.get('tensorflow')} (Keras 3) |
| Hardware | CPU only ({env.get('platform')}) |
| Optimiser / loss | Adam, sparse categorical cross-entropy |
| Callbacks | EarlyStopping (patience {C.EARLY_STOPPING_PATIENCE}, restore best), ReduceLROnPlateau (×0.5, patience {C.REDUCE_LR_PATIENCE}), ModelCheckpoint |
| Seed | {C.SEED} |

{training_table()}

## 10. Evaluation Metrics

*Accuracy* is the fraction of correct predictions. *Precision* is the fraction of predictions of a class
that are correct; *recall* the fraction of a class that is found; *F1* their harmonic mean. *Macro*
averages give every class equal weight. The *confusion matrix* shows which classes are confused.
*Training time* and *inference time per image* (median of 3 timed batch predictions after a warm-up)
measure cost.

## 11. Results

All metrics are on the held-out test set ({rs[0]['test_samples']} images, never used for training or model selection
during training).

{results_table(rs)}

![Model comparison](../results/graphs/model_comparison.png)

![Computational cost](../results/graphs/comparison_time.png)

### Per-class F1-score

{per_class_table(rs)}

### Training curves

{chr(10).join(f"![{n} accuracy](../results/graphs/{c['slug']}_accuracy.png)" for n, c in C.MODELS.items() if n in by)}

## 12. Confusion Matrix Analysis

{chr(10).join(conf_sections)}

## 13. Model Comparison and Best Model Selection

Rule: highest macro F1; if within {C.TIE_MARGIN}, higher accuracy, then faster inference.

**Selected model: {best['model_name']}** (macro F1 {_f(best['metric_value'])}, accuracy {_f(best['accuracy'])}).
{best['reason']}

Fastest inference: {fastest['model']} ({_f(fastest['inference_time_ms_per_image'], 3)} ms/image).

## 14. Prediction Application

`src/predict.py` loads the model named in `results/reports/best_model.json`, applies the same
preprocessing as training and returns the predicted class, confidence, a confidence interpretation
(≥ 90 % very high, ≥ 70 % high, ≥ 50 % moderate, otherwise low) and the probabilities of all nine classes.
It validates that the file exists, has a supported format, can be opened and is at least 8 × 8 pixels.
`app/app.py` wraps it in a Gradio web interface (upload, preview, predict, probability chart, active
model, disclaimer). The model is loaded once at start-up; nothing is retrained.

## 15. Discussion

- Ranking by macro F1: {ranking}. The best model reaches {_f(best_r['accuracy'] if best_r else None)} test accuracy.
- The errors concentrate on classes that differ mainly in size/location of a small cluster (see
  the confusion matrices) — e.g. a small Center blob vs. a Loc blob near the centre, or a short Scratch
  vs. an elongated Loc. This matches the physical ambiguity of these patterns.
- Large pretrained networks are not automatically better here: the maps are tiny, binary-like images,
  very different from ImageNet photographs, and a compact CNN trained from scratch can learn their spatial
  patterns directly at a fraction of the cost.
- Because the test set has only {rs[0]['test_samples']} images (15 per class), one misclassification changes accuracy by
  {100 / rs[0]['test_samples']:.2f} percentage points; small differences between models should not be over-interpreted.

## 16. Limitations

- The dataset is synthetic; real wafer maps (e.g. WM-811K) contain noisier, mixed and rarer patterns.
- 900 images and 15 test images per class give limited statistical power.
- Classes are balanced, unlike real production data where *None* dominates.
- Results come from a single training run (seed {C.SEED}) on CPU.
- The system classifies wafer-map patterns; it does not inspect physical dies or camera images.
- The prototype has not been validated or deployed in a semiconductor fab.

## 17. Future Work

- Train and test on the real WM-811K dataset, with class-imbalance handling.
- Repeat training with several seeds and report mean ± standard deviation.
- Fine-tune the upper layers of the pretrained backbones.
- Grad-CAM heatmaps to show which wafer region drives each prediction.
- Detection of unseen patterns (low-confidence / anomaly detection) and mixed-defect classification.

## 18. Conclusion

The project delivers a working, reproducible wafer defect pattern classifier: validated synthetic data,
EDA, a leakage-free fixed split, three trained models compared on identical data, automatic best-model
selection ({best['model_name']}), a prediction engine and a web application, plus an automated test suite.

## 19. References

1. Wu, M.-J., Jang, J.-S. R., Chen, J.-L. "Wafer Map Failure Pattern Recognition and Similarity Ranking
   for Large-Scale Data Sets." *IEEE Trans. Semiconductor Manufacturing*, 28(1), 2015 (WM-811K).
2. He, K., Zhang, X., Ren, S., Sun, J. "Deep Residual Learning for Image Recognition." CVPR, 2016.
3. Tan, M., Le, Q. "EfficientNet: Rethinking Model Scaling for Convolutional Neural Networks." ICML, 2019.
4. TensorFlow / Keras documentation — keras.io.
5. Pedregosa et al. "Scikit-learn: Machine Learning in Python." JMLR 12, 2011.
6. Gradio documentation — gradio.app.

## 20. Use of Generative AI

Generative AI (Claude) assisted with structuring the project, writing code, generating the synthetic
dataset generator and drafting this report. All experiments were executed and every reported metric was
produced by the project code and inserted automatically from the result files. The team reviewed the code
and results.
"""


def main() -> int:
    eda, res, best = _load("eda_summary.json"), _load("all_model_results.json"), _load("best_model.json")
    summary = _load("final_project_summary.json")
    if not (eda and res and best):
        print("Missing results. Run: python run_project.py all")
        return 1
    C.REPORT_DOC_DIR.mkdir(exist_ok=True)
    REPORT.write_text(build_report(eda, res, best, summary), encoding="utf-8")
    update_readme(res, best)
    print(f"Wrote {REPORT.relative_to(C.BASE_DIR)} and updated README results section.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
